// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IVscodeIconsFileTypeEslint: typeof import('~icons/vscode-icons/file-type-eslint')['default']
    IVscodeIconsFileTypePnpm: typeof import('~icons/vscode-icons/file-type-pnpm')['default']
    IVscodeIconsFileTypeTypescript: typeof import('~icons/vscode-icons/file-type-typescript')['default']
    IVscodeIconsFileTypeVitest: typeof import('~icons/vscode-icons/file-type-vitest')['default']
  }
}
