export type { App } from '~bridges/types.ts'
export { attrsListenersMixin } from './attrs-listeners'
export { defineDirective } from './customDirectives'
export { defineComponent } from './defineComponent'
export { isVue2 } from './constants'
export { set, del } from '~bridges/set-delete.ts'
